include common.mk

default: dist

# pgxn packaging
$(TMP_DIR)/META.json: META.json.in
	@mkdir -p $(TMP_DIR)
	@sed "s/@PG_TRACING_VERSION@/$(EXT_VERSION)/g" $< > $@

$(TMP_DIR)/$(EXTENSION)-$(EXT_VERSION).zip: $(TMP_DIR)/META.json
	@git archive --format zip --prefix "$(EXTENSION)-$(EXT_VERSION)/" --add-file $< -o "$(TMP_DIR)/$(EXTENSION)-$(EXT_VERSION).zip" HEAD
	@echo "artifact=$(TMP_DIR)/$(EXTENSION)-$(EXT_VERSION).zip"

dist: $(TMP_DIR)/$(EXTENSION)-$(EXT_VERSION).zip
