# Build and publish the pg_tracing extension to the PostgreSQL Extension Network (PGXN).

name: Publish pg_tracing (PGXN)

permissions: {}

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish-pg_tracing:
    name: Publish pg_tracing to PGXN
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    permissions:
      contents: read
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          fetch-depth: 0

      - id: dist
        name: Bundle the Release
        run: make -s dist >> "$GITHUB_OUTPUT"

      - name: Release on PGXN
        env:
          PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
        run: pgxn-release ${{ steps.dist.outputs.artifact }}
