# Build and publish the pg_tracing extension to the PostgreSQL Extension Network (PGXN).

name: Publish pg_tracing (PGXN)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish-pg_tracing:
    name: Publish pg_tracing to PGXN
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bundle the Release
        run: make dist
      - name: Release on PGXN
        env:
          PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
        run: pgxn-release
