name: Run Tests

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_tests:
    name: Run test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        PG_VERSION: [14, 15, 16, 17, 18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set environment variables
        run: echo "PG_VERSION=${{ matrix.PG_VERSION }}" >> $GITHUB_ENV
      - name: Add gcc problem matcher
        run: echo "::add-matcher::matcher.json"
      - name: Build Docker Test Image
        run: make build-test-image
      - name: Check pgindent
        # pgindent is only available starting PG 17
        if: ${{ matrix.PG_VERSION > 16 }}
        run: make run-pgindent-diff
      - name: Run Test
        timeout-minutes: 1
        run: make run-test
